TOKEN_API = "6106250764:AAHV-jZy1rkHGDK2OCfCHxQ9Sq42i7wSIDU"
role = "Выберите свою роль!"
admin_hello = "приветствую вас!\nВыберите шаг!"
not_admin_hello = "Прошу зарегестрироваться как студент!"
stud_hello = "Приветсвуем вас вновь!"
call_to_reg = "Вижу вы тут впервые, проейдем регистрацию?"